// <auto-generated />
using System;
using DataAccess.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20251118173419_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RegionId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "New York",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Philadelphia",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Washington D.C.",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Los Angeles",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "San Francisco",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Las Vegas",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "London",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "Paris",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "Vienna",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tokyo",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 11,
                            Name = "Osaka",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 12,
                            Name = "Busan",
                            RegionId = 4
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Conditions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sunny weather",
                            Name = "Sunny"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cloudy weather",
                            Name = "Cloudy"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Rainy weather",
                            Name = "Rainy"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Stormy weather",
                            Name = "Stormy"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Snowy weather",
                            Name = "Snowy"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "US-East"
                        },
                        new
                        {
                            Id = 2,
                            Name = "US-West"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Europe"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Asia"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.WeatherData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("ConditionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<float>("HumidityPercent")
                        .HasColumnType("real");

                    b.Property<float>("TemperatureCelsius")
                        .HasColumnType("real");

                    b.Property<float>("WindSpeedKph")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ConditionId");

                    b.HasIndex("CityId", "Date")
                        .IsUnique();

                    b.ToTable("WeatherDatas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            ConditionId = 1,
                            Date = new DateTime(2025, 7, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 65f,
                            TemperatureCelsius = 28.5f,
                            WindSpeedKph = 12.5f
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            ConditionId = 3,
                            Date = new DateTime(2025, 4, 10, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 88f,
                            TemperatureCelsius = 15.2f,
                            WindSpeedKph = 8f
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            ConditionId = 5,
                            Date = new DateTime(2025, 1, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 75f,
                            TemperatureCelsius = -1f,
                            WindSpeedKph = 20f
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            ConditionId = 1,
                            Date = new DateTime(2025, 8, 20, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 60f,
                            TemperatureCelsius = 31f,
                            WindSpeedKph = 15f
                        },
                        new
                        {
                            Id = 5,
                            CityId = 2,
                            ConditionId = 2,
                            Date = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 70f,
                            TemperatureCelsius = 18.5f,
                            WindSpeedKph = 10f
                        },
                        new
                        {
                            Id = 6,
                            CityId = 2,
                            ConditionId = 4,
                            Date = new DateTime(2025, 9, 25, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 90f,
                            TemperatureCelsius = 16f,
                            WindSpeedKph = 25f
                        },
                        new
                        {
                            Id = 7,
                            CityId = 3,
                            ConditionId = 1,
                            Date = new DateTime(2025, 6, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 55f,
                            TemperatureCelsius = 26f,
                            WindSpeedKph = 11f
                        },
                        new
                        {
                            Id = 8,
                            CityId = 3,
                            ConditionId = 2,
                            Date = new DateTime(2025, 12, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 80f,
                            TemperatureCelsius = 4.5f,
                            WindSpeedKph = 5f
                        },
                        new
                        {
                            Id = 9,
                            CityId = 3,
                            ConditionId = 3,
                            Date = new DateTime(2025, 3, 18, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 92f,
                            TemperatureCelsius = 8.2f,
                            WindSpeedKph = 18f
                        },
                        new
                        {
                            Id = 10,
                            CityId = 4,
                            ConditionId = 1,
                            Date = new DateTime(2025, 9, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 35f,
                            TemperatureCelsius = 32f,
                            WindSpeedKph = 5f
                        },
                        new
                        {
                            Id = 11,
                            CityId = 4,
                            ConditionId = 2,
                            Date = new DateTime(2025, 11, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 50f,
                            TemperatureCelsius = 21f,
                            WindSpeedKph = 10f
                        },
                        new
                        {
                            Id = 12,
                            CityId = 4,
                            ConditionId = 3,
                            Date = new DateTime(2025, 2, 28, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 75f,
                            TemperatureCelsius = 17.5f,
                            WindSpeedKph = 8.5f
                        },
                        new
                        {
                            Id = 13,
                            CityId = 5,
                            ConditionId = 2,
                            Date = new DateTime(2025, 7, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 78f,
                            TemperatureCelsius = 19.5f,
                            WindSpeedKph = 30f
                        },
                        new
                        {
                            Id = 14,
                            CityId = 5,
                            ConditionId = 1,
                            Date = new DateTime(2025, 10, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 60f,
                            TemperatureCelsius = 24f,
                            WindSpeedKph = 15f
                        },
                        new
                        {
                            Id = 15,
                            CityId = 5,
                            ConditionId = 3,
                            Date = new DateTime(2025, 3, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 85f,
                            TemperatureCelsius = 13f,
                            WindSpeedKph = 18f
                        },
                        new
                        {
                            Id = 16,
                            CityId = 6,
                            ConditionId = 1,
                            Date = new DateTime(2025, 8, 5, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 15f,
                            TemperatureCelsius = 40.5f,
                            WindSpeedKph = 10f
                        },
                        new
                        {
                            Id = 17,
                            CityId = 6,
                            ConditionId = 1,
                            Date = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 30f,
                            TemperatureCelsius = 14f,
                            WindSpeedKph = 5f
                        },
                        new
                        {
                            Id = 18,
                            CityId = 6,
                            ConditionId = 2,
                            Date = new DateTime(2025, 12, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 45f,
                            TemperatureCelsius = 8.8f,
                            WindSpeedKph = 12f
                        },
                        new
                        {
                            Id = 19,
                            CityId = 7,
                            ConditionId = 2,
                            Date = new DateTime(2025, 6, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 75f,
                            TemperatureCelsius = 18f,
                            WindSpeedKph = 10f
                        },
                        new
                        {
                            Id = 20,
                            CityId = 7,
                            ConditionId = 3,
                            Date = new DateTime(2025, 10, 5, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 90f,
                            TemperatureCelsius = 12.5f,
                            WindSpeedKph = 15f
                        },
                        new
                        {
                            Id = 21,
                            CityId = 7,
                            ConditionId = 1,
                            Date = new DateTime(2025, 7, 28, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 55f,
                            TemperatureCelsius = 25.5f,
                            WindSpeedKph = 8f
                        },
                        new
                        {
                            Id = 22,
                            CityId = 8,
                            ConditionId = 1,
                            Date = new DateTime(2025, 8, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 50f,
                            TemperatureCelsius = 30f,
                            WindSpeedKph = 10f
                        },
                        new
                        {
                            Id = 23,
                            CityId = 8,
                            ConditionId = 3,
                            Date = new DateTime(2025, 4, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 65f,
                            TemperatureCelsius = 14f,
                            WindSpeedKph = 18f
                        },
                        new
                        {
                            Id = 24,
                            CityId = 8,
                            ConditionId = 2,
                            Date = new DateTime(2025, 11, 1, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 75f,
                            TemperatureCelsius = 9.5f,
                            WindSpeedKph = 5f
                        },
                        new
                        {
                            Id = 25,
                            CityId = 9,
                            ConditionId = 1,
                            Date = new DateTime(2025, 9, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 60f,
                            TemperatureCelsius = 22f,
                            WindSpeedKph = 15f
                        },
                        new
                        {
                            Id = 26,
                            CityId = 9,
                            ConditionId = 5,
                            Date = new DateTime(2025, 2, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 80f,
                            TemperatureCelsius = 2f,
                            WindSpeedKph = 5f
                        },
                        new
                        {
                            Id = 27,
                            CityId = 9,
                            ConditionId = 4,
                            Date = new DateTime(2025, 7, 5, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 45f,
                            TemperatureCelsius = 29.5f,
                            WindSpeedKph = 25f
                        },
                        new
                        {
                            Id = 28,
                            CityId = 10,
                            ConditionId = 3,
                            Date = new DateTime(2025, 8, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 85f,
                            TemperatureCelsius = 33f,
                            WindSpeedKph = 10f
                        },
                        new
                        {
                            Id = 29,
                            CityId = 10,
                            ConditionId = 1,
                            Date = new DateTime(2025, 11, 25, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 60f,
                            TemperatureCelsius = 17.5f,
                            WindSpeedKph = 12f
                        },
                        new
                        {
                            Id = 30,
                            CityId = 10,
                            ConditionId = 2,
                            Date = new DateTime(2025, 1, 15, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 70f,
                            TemperatureCelsius = 6f,
                            WindSpeedKph = 5f
                        },
                        new
                        {
                            Id = 31,
                            CityId = 11,
                            ConditionId = 4,
                            Date = new DateTime(2025, 7, 1, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 90f,
                            TemperatureCelsius = 30.5f,
                            WindSpeedKph = 20f
                        },
                        new
                        {
                            Id = 32,
                            CityId = 11,
                            ConditionId = 2,
                            Date = new DateTime(2025, 4, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 75f,
                            TemperatureCelsius = 15f,
                            WindSpeedKph = 8f
                        },
                        new
                        {
                            Id = 33,
                            CityId = 11,
                            ConditionId = 1,
                            Date = new DateTime(2025, 12, 18, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 65f,
                            TemperatureCelsius = 8f,
                            WindSpeedKph = 10f
                        },
                        new
                        {
                            Id = 34,
                            CityId = 12,
                            ConditionId = 1,
                            Date = new DateTime(2025, 6, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 70f,
                            TemperatureCelsius = 25f,
                            WindSpeedKph = 18f
                        },
                        new
                        {
                            Id = 35,
                            CityId = 12,
                            ConditionId = 3,
                            Date = new DateTime(2025, 10, 25, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 80f,
                            TemperatureCelsius = 17f,
                            WindSpeedKph = 5f
                        },
                        new
                        {
                            Id = 36,
                            CityId = 12,
                            ConditionId = 2,
                            Date = new DateTime(2025, 3, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            HumidityPercent = 72f,
                            TemperatureCelsius = 9.5f,
                            WindSpeedKph = 14f
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.City", b =>
                {
                    b.HasOne("DataAccess.Entities.Region", "Region")
                        .WithMany("Cities")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("DataAccess.Entities.WeatherData", b =>
                {
                    b.HasOne("DataAccess.Entities.City", "City")
                        .WithMany("WeatherData")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Condition", "Condition")
                        .WithMany("WeatherData")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Condition");
                });

            modelBuilder.Entity("DataAccess.Entities.City", b =>
                {
                    b.Navigation("WeatherData");
                });

            modelBuilder.Entity("DataAccess.Entities.Condition", b =>
                {
                    b.Navigation("WeatherData");
                });

            modelBuilder.Entity("DataAccess.Entities.Region", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
